imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

doctrine:
  orm:
    auto_generate_proxy_classes: false
    metadata_cache_driver:
      type: service
      id: doctrine_cache.metadata
    query_cache_driver:
      type: service
      id: doctrine_cache.query
    result_cache_driver:
      type: service
      id: doctrine_cache.result

  dbal:
    logging: false
    profiling: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console

assetic:
    node: /opt/cpanel/ea-nodejs16/bin/node
    filters:
      handlebars:
        bin: /home/gxpvsxmy/Servers/swdestinydb/node_modules/handlebars/bin/handlebars
        node: /opt/cpanel/ea-nodejs16/bin/node

fos_js_routing:
  routes_to_expose:
    - user_info
    - api_formats
    - '^api_'
