# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  doctrine_cache.metadata:
    class: Doctrine\Common\Cache\FilesystemCache
    arguments: ["%kernel.cache_dir%/doctrine/metadata"]

  doctrine_cache.query:
    class: Doctrine\Common\Cache\FilesystemCache
    arguments: ["%kernel.cache_dir%/doctrine/query"]

  doctrine_cache.result:
    class: Doctrine\Common\Cache\FilesystemCache
    arguments: ["%kernel.cache_dir%/doctrine/result"]

